services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      ACCEPT_EULA : "1"
      MSSQL_SA_PASSWORD: "Password@1"
    platform: "linux/amd64"
    ports:
      - "1433:1433"